#### CREATE CONTROLDICT ####
def generate_controlDict(header_dict = {
    "version":     2.0,
    "format":      "ascii",
    "class":       "dictionary",
    "object":      "controlDict",
}, 
control_dict_template = {
    "application": "simpleFoam",        # Dropdown: simpleFoam, icoFoam, pimpleFoam
    "startFrom": "startTime",           # Dropdown: startTime, firstTime, latestTime
    "startTime": 0,                     # Number input
    "stopAt": "endTime",                # Dropdown: endTime, writeTime, noWriteNow
    "endTime": 1000,                    # Number input  
    "deltaT": 1,                        # Number input
    "writeControl": "runTime",          # Dropdown: runTime, timeStep, adjustableRunTime
    "writeInterval": 100,               # Number input
    "purgeWrite": 0,                    # Number input
    "writeFormat": "binary",            # Dropdown: ascii, binary
    "writePrecision": 6,                # Slider: 2-16
    "writeCompression": "off",          # Dropdown: on, off
    "timeFormat": "general",            # Dropdown: general, fixed, scientific
    "timePrecision": 6,                 # Slider: 2-16
    "runTimeModifiable": True,          # Checkbox
    "adjustTimeStep": "no",             # Dropdown: yes, no
    "maxCo": 0.5,                       # Slider: 0.1-2.0
}
):

    controlDict = OpenFOAMDict()
    controlDict.add_comment("Autogenerated with PoreMesh by SKD3")
    controlDict.start_dict("FoamFile")
    for elem in header_dict:
        controlDict.add_entry(elem, header_dict[elem])
    controlDict.end_dict()
    
    
    
    for elem in control_dict_content:
        controlDict.add_entry(elem, control_dict_content[elem])
    
    controlDict.start_dict("functions")
    controlDict.add_entry("#include", '"FOs"', terminator="")
    controlDict.end_dict(terminator=";")
    
    controlDict.start_list("libs")
    controlDict.end_list()
    
    controlDict.content
    blockMeshDict.write(Path("Data/TS-01/controlDict.test"))